apiVersion: v1
kind: ServiceAccount
metadata:
  name: recoverops
  namespace: sre-lab
  labels:
    app.kubernetes.io/part-of: sre-portfolio
    app.kubernetes.io/component: recoverops
automountServiceAccountToken: true
